- .github/workflows/check.yml
- requirements-test.txt
https://github.com/pytest-dev/py/issues/273 has now been released so we can remove the workaround.
> Remove py workaround

- setup.cfg
Not sure why this was added in the first place. Conceptually better to
not do that, but to use regular install instead.
> test(tox): do not install in develop mode

- pyproject.toml
- requirements-dev.txt
`fail-on` is available since pylint 2.9.0.
> chore(pylint): replace strict-informational plugin with `fail-on=I`

- pyproject.toml
Not bumping/marking any required versions for this, instead assuming setups running pre-release Python 3.11 are also installing new enough dependencies to go with that.
> test(py311): remove no longer needed yarl and frozenlist "no extensions"

- MANIFEST.in
Commit 134eec2b9990d06f24ab8af42f6372e55ecd9b73 did fix it originally, but 75b9735998f1d29f50b830d7d45ee1184cec8230 broke it again. It went unnoticed and got included in my local tests because there was stale `src/pytekukko.egg-info` from a previous fixed build around.
Re-fix by including in `MANIFEST.in` per
https://setuptools.pypa.io/en/stable/userguide/datafiles.html#include-package-data
> fix(dist): actually include `py.typed`

- .github/workflows/check.yml
- pyproject.toml
tox envs need to be configured anyway even with tox-gh-actions, so we might as well configure them in the CI job matrix where they're better placed than in the global tox config when using tox-gh-actions.
Dropping dependency on tox-gh-actions results in more freedom with regards to tox versions.
> ci(tox): do without tox-gh-actions

- .github/workflows/check.yml
> ci: exclude venv activation from shell trace output

- .github/renovate.json
This reverts commit 173d53458e885a4509da4cb9114f40221b888cee.
Renovate's semver does not seem to strip the `==` we have in the requirements-dev.txt version.
> ci(renovate): set ruff versioning back to pep440

- src/pytekukko/examples/__init__.py
- src/pytekukko/examples/print_collection_schedules.py
- src/pytekukko/examples/print_invoice_headers.py
- src/pytekukko/examples/print_next_collections.py
- src/pytekukko/examples/update_google_calendar.py
At least for now, for some compatibility with original non-ruff implementations.
> chore(lint): use codes with `noqa`

- .github/renovate.json
- .pre-commit-config.yaml
- pyproject.toml
- requirements-dev.txt
- requirements-test.txt
For updating additional PyPI dependencies in `.pre-commit-config.yaml` (just one remains though).
Allows formatting versioned dependencies without whitespace hacks there; take advantage of it and remove the weirdness everywhere.
> ci(renovate): use regex manager instead of a pip requirements hack

- noxfile.py
Disabling the extensions seems no longer needed as of Python 3.12.0b1.
> test(nox): build with aiohttp, frozenlist and yarl extensions

- noxfile.py
Seemingly necessary again as of Python 3.12.0b2.
> test(nox): skip aiohttp and frozenlist native builds with Python 3.12

- .github/workflows/check.yml
- noxfile.py
- pyproject.toml
- src/pytekukko/__init__.py
- src/pytekukko/examples/__init__.py
- src/pytekukko/models.py
Dropped in current HA a while back, and Debian Bookworm comes with 3.11.
> refactor: drop Python 3.9 support

- .github/workflows/release.yml
The default Python for an up to date `ubuntu-latest` image should be a good enough, maintenance free default in the usual case.
https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md
> ci(release): drop separate setup-python action

- noxfile.py
Disabling the extensions seems no longer needed as of Python 3.12.0 and current lib version.
> test(nox): build frozenlist with extensions

- .github/workflows/release.yml
The google-github-actions one is deprecated and archived.
> ci: switch release-please action to googleapis one, upgrade to 4.1.3

- .github/renovate.json
- .github/workflows/update-tools.yaml
Does not appear to work after all on some quick tries, let it be for now.
This reverts commit 3aeb99b8f69a4ac1fe755350c87fd0cc416ebf7e. This reverts commit fe80736874338b3b8077bd0b75d5ed8a54d18c8f.
> chore(ci): revert renovate committed config attempts

- .lefthook.yaml
As we install it with uv too (not mise).
> chore(lefthook): run ruff through uv

- .config/mise.toml
- .lefthook.yaml
- requirements/dev-requirements.txt
With mise we have better control over the version of ruff installed when done through lefthook. A stray ruff install that precedes the mise installed one in PATH can still wreak havoc, though.
> chore(ruff): run and install with mise instead of uv

- noxfile.py
- requirements/test-requirements.txt
To avoid having to exclude a deprecation warning.
> chore(deps): require pytest-asyncio >=0.25

- pyproject.toml
> chore(deps): allow icalendar 6
